# Project information
site_name: 'Genyman'
site_description: 'Genyman - A .net core cli code generator'
site_author: 'Stefan de Vogelaere'
site_url: 'https://genyman.github.io/'

# Repository
repo_name: 'genyman/docs'
repo_url: 'https://github.com/genyman/docs'
edit_uri: 'edit/master/mkdocs/docs'

# Copyright
copyright: 'Copyright &copy; 2018 Stefan de Vogelaere'

# Configuration
theme: 
  name: material
  logo: 'images/genyman.svg'
  favicon: 'images/favicon.ico'
  palette:
    primary: 'blue grey'
    accent: 'blue'

# Google Analytics
google_analytics:
  - 'UA-37056204-9'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

# Pages
pages:
- 'Introduction': 'index.md'
- 'Getting started': 'getting_started.md'
- Reference:
    - 'Genyman Cli': 'reference/genyman-cli.md'
    - 'Genyman Core': 'reference/genyman-core.md'
    - 'Handlebars Helpers': 'reference/handlebars-helpers.md'
    - 'FluentMSBuild': 'reference/fluent-msbuild.md'
- 'Troubleshooting': 'troubleshooting.md'
- 'Community': 'community.md'